- hosts: dev
  become: true
  roles:
    - python
    - docker
    - docker-compose
  tasks:
  - name: create git dir
    file:
      state: directory
      path: /home/qazyb/MealGen-QA-Project2
  - name: clone repo
    git:
      repo: https://github.com/Qaz786i/MealGen-QA-Project2/
      dest: /home/qazyb/MealGen-QA-Project2
      clone: yes
  vars:
    docker_user: qazyb

- hosts: ciservers
  become: true
  roles:
  - python
  - docker
  - docker-compose
  - jenkins
  vars:
    docker_user: jenkins

- hosts: swarmmanagers
  become: true
  roles:
    - docker
    - swarm-manager
  tasks:
  - name: add ansible user to docker group
    user:
      name: qazyb
      groups: docker
      append: yes
  vars:
    docker_user: jenkins

- hosts: swarmworkers
  become: true
  roles:
    - docker
    - swarm-worker
  vars:
    docker_user: qazyb